apiVersion: v1
kind: Service
metadata:
  name: website-gateway
  namespace: pizza
  labels:
    app: website-gateway
  annotations:
    prometheus.io/path: /actuator/prometheus                                                                                                                                                                                                                                 │
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - port: 8999
    targetPort: 8999
    protocol: TCP
  selector:
    app: website-gateway
