apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-gateway
  namespace: pizza
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website-gateway
    spec:
      containers:
      - name: website-gateway
        image: <replaced_at_deploy_time>
        imagePullPolicy: Always
        env:
          - name: BOOTIFUL_MICRO_PIZZA_ENV
            value: prod
          - name: CONFIG_LOCATION
            value: https://github.com/bootifulmicropizza/configuration.git
          - name: BUILD_DATE
            value: BUILD_DATE_PLACEHOLDER
        resources:
          requests:
            cpu: "0.25"
            memory: 768Mi
          limits:
            cpu: "1"
            memory: 1024Mi
        ports:
        - containerPort: 8999
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8999
          initialDelaySeconds: 120
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8999
          initialDelaySeconds: 30
          timeoutSeconds: 5
